# action.yml
name: "action-sync"
description: "sync file to organization all repositories"
author: myml
branding:
  icon: align-center
  color: "white"
inputs:
  files:
    description: "config files"
    required: true
  message:
    description: "commit message"
    required: false
    default: "chore: Sync by .github"

runs:
  using: "composite"
  steps:
    - uses: actions/setup-go@v2
      with:
        go-version: ^1.17.1
    - name: Install binary
      shell: bash
      run: |
        cd $GITHUB_ACTION_PATH
        go build
    - name: Sync
      shell: bash
      run: |
        echo "${{ inputs.files }}" | xargs -d ' ' -i sh '$GITHUB_ACTION_PATH/action-sync -files="{}" -message="${{ inputs.message }}" || exit 255'
